# Generated by Django 5.0.8 on 2024-12-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepts', '0002_recipe_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='recipes',
        ),
    ]
